SexyLib:InitLocalization('Classic Achievements', {
    achievement_earned = '&aAchievement earned by %s on %d/%d/%d',
    achievement_in_progress = '&7Achievement in progress by %s',

    ICON_DESCRIPTION = '&7Left mouse button: &eopen/hide achievements window\n&7Right mouse button: &eopen Classic Achievements settings\n\n&3With love from Maxich :)',

    OPTION_SHARING = 'Share achievements',
    OPTION_SHARING_DESC = 'Whether to write messages in chats when receiving new achievement.',
    OPTION_MICROBUTTON = 'Micromenu button',
    OPTION_MICROBUTTON_DESC = 'If enabled, an addon button will be added to the micromenu, and the interface may break if you are using any addon to modify it. If disabled, the icon will be added to the minimap. Toggling this option requires you to do /reload or rejoin your character.',
    OPTION_UPDATE_MAP_EXPLORATION = 'Check explored locations',
    OPTION_UPDATE_MAP_EXPLORATION_DESC = 'Counts already explored locations for achievements.',
    OPTION_RESET_ACHIEVEMENTS = 'Reset achievements',
    OPTION_RESET_ACHIEVEMENTS_DESC = 'Reset all achievements progressions on this character. This can not be undone!',

    GOT_ACHIEVEMENT_MESSAGE_MALE = 'I\'ve just earned achievement %s!',
    GOT_ACHIEVEMENT_MESSAGE_FEMALE = 'I\'ve just earned achievement %s!',

    COMPARE_ACHIEVEMENTS = 'Compare achievements',
    TARGET_DOES_NOT_HAVE_ADDON = 'Target does not have this addon installed.',

    UPDATING_EXPLORED_AREAS = 'Updating locations exploration data. This action will take a few seconds.',
    UPDATED_EXPLORED_AREAS = '&aInformation about explored locations has been updated!',

    NOT_WORKING = 'not working',

    GEAR_SLOT_HEAD = 'Headdress',
    GEAR_SLOT_NECK = 'Necklace',
    GEAR_SLOT_SHOULDER = 'Shoulders',
    GEAR_SLOT_CHEST = 'Chest armor',
    GEAR_SLOT_WAIST = 'Waist',
    GEAR_SLOT_LEGS = 'Leggings',
    GEAR_SLOT_FEET = 'Boots',
    GEAR_SLOT_WRIST = 'Wrist',
    GEAR_SLOT_HANDS = 'Gloves',
    GEAR_SLOT_FIRST_RING = 'First ring',
    GEAR_SLOT_SECOND_RING = 'Second ring',
    GEAR_SLOT_FIRST_TRINKET = 'First trinket',
    GEAR_SLOT_SECOND_TRINKET = 'Second trinket',
    GEAR_SLOT_CLOAK = 'Cloak',
    GEAR_SLOT_WEAPON = 'Weapon',

    NPC_3444 = 'Dig rat',
    NPC_620 = 'Chicken',
    NPC_1420 = 'Toad',
    NPC_13321 = 'Frog',
    NPC_2620 = 'Prairie Dog',
    NPC_9600 = 'Parrot',
    NPC_5951 = 'Hare',
    NPC_9699 = 'Fire Beetle',
    NPC_4953 = 'Moccasin',
    NPC_721 = 'Rabbit',
    NPC_9700 = 'Lava Crab',
    NPC_15476 = 'Scorpion',
    NPC_2914 = 'Snake',
    NPC_16030 = 'Maggot',
    NPC_4075 = 'Rat',
    NPC_1412 = 'Squirrel',
    NPC_7390 = 'Cockatiel',
    NPC_15475 = 'Beetle',
    NPC_15010 = 'Jungle Toad',
    NPC_4076 = 'Roach',
    NPC_13016 = 'Deeprun Rat',
    NPC_14881 = 'Spider',
    NPC_2110 = 'Black Rat',
    NPC_4166 = 'Gazelle',
    NPC_1933 = 'Sheep',
    NPC_890 = 'Fawn',
    NPC_2098 = 'Ram',
    NPC_2442 = 'Cow',
    NPC_6368 = 'Cat',
    NPC_10582 = 'Dog',
    NPC_385 = 'Horse',
    NPC_10685 = 'Swine',
    NPC_3300 = 'Adder',
    NPC_15066 = 'Cleo',
    NPC_15071 = 'Underfoot',

    CATEGORY_GENERAL = 'General',
    CATEGORY_QUESTS = 'Quests',
    CATEGORY_KALIMDOR = 'Kalimdor',
    CATEGORY_EASTERN_KINGDOMS = 'Eastern Kingdoms',
    CATEGORY_OUTLAND = 'Outland',
    CATEGORY_VANILLA = 'Classic Experience',
    CATEGORY_TBC = 'The Burning Crusade',
    CATEGORY_EXPLORATION = 'World Exploration',
    CATEGORY_PVE = 'Dungeons and Raids',
    CATEGORY_BATTLEGROUNDS = 'Battlegrounds',
    CATEGORY_BG_ALTERAC = 'Alterac Valley',
    CATEGORY_BG_WARSONG = 'Warsong Gulch',
    CATEGORY_BG_ARATHI = 'Arathi Basin',
    CATEGORY_BG_EYE = 'Eye of the Storm',
    CATEGORY_OPEN_WORLD = 'Open World',
    CATEGORY_PROFESSIONS = 'Professions',
    CATEGORY_REPUTATION = 'Reputations',
    CATEGORY_FEATS_OF_STRENGTH = 'Feats of Strength',
    CATEGORY_EVENTS = 'Game Events',

    AN_LVL = 'Level %d',
    AD_LVL = 'Reach level %d.',

    AN_BANK = 'Bank cell',
    AD_BANK = 'Purchase all additional slots in the bank.',
    AC_BANK = 'Purchased all additional slots in the bank.',

    AN_QUESTS = '%d quests',
    AD_QUESTS = 'Complete %d quests.',
    AC_QUESTS = 'Completed %d quests.',

    AN_QUEST_GOLD5 = 'Glittering reward',
    AN_QUEST_GOLD10 = 'Collector of minted coins',
    AN_QUEST_GOLD25 = 'Breadwinner',
    AN_QUEST_GOLD50 = 'Well-deserved Gold',
    AN_QUEST_GOLD100 = 'Earned by sweat and blood',
    AN_QUEST_GOLD250 = 'Golden Printer',
    AN_QUEST_GOLD500 = 'I\'m Mint Myself',
    AD_QUEST_GOLD = 'Earn %d golden coins by completing quests.',
    AC_QUEST_GOLD = 'Earned %d golden coins by completing quests.',

    AN_QUESTS_ZONE = 'Wisdom Keeper of %s',
    AD_QUESTS_ZONE = 'Complete quest "%s" in %s.',
    AD_QUESTS_ZONE_MULTI = 'Complete the following quests in %s.',
    AC_QUESTS_ZONE = 'Completed quest "%s".',

    AZSHARA_1 = 'Azshara',
    AZSHARA_2 = 'Azshara',
    QUEST_3602 = 'Azsharite',

    FELWOOD_1 = 'Felwood',
    FELWOOD_2 = 'Felwood',
    QUEST_5165 = 'Dousing the Flames of Protection',
    QUEST_5385 = 'The Remains of Trey Lightforge',

    DESOLACE_1 = 'Desolace',
    DESOLACE_2 = 'Desolace',
    QUEST_6027 = 'Book of the Ancients',

    DUSTWALLOW_1 = 'Dustwallow marsh',
    DUSTWALLOW_2 = 'Dustwallow marsh',
    QUEST_1203 = 'Jarl Needes a Blade',

    SILITHUS_1 = 'Silithus',
    SILITHUS_2 = 'Silithus',
    QUEST_8287 = 'A Terrible Purpose',
    QUEST_8352 = 'Scepter of the Council',
    QUEST_8321 = 'Vyral the Vile',
    QUEST_8281 = 'Stepping Up Security',

    DUROTAR_1 = 'Durotar',
    DUROTAR_2 = 'Durotar',
    QUEST_835 = 'Securing the Lines',

    BARRENS_1 = 'The Barrens',
    BARRENS_2 = 'The Barrens',
    QUEST_888 = 'Stolen Booty',
    QUEST_902 = 'Samophlange',

    WINTERSPRING_1 = 'Winterspring',
    WINTERSPRING_2 = 'Winterspring',
    QUEST_975 = 'Cache of Mau\'ari',
    QUEST_5082 = 'Threat of the Winterfall',
    QUEST_5121 = 'High Chief Winterfall',
    QUEST_5163 = 'Are We There, Yeti?',
    QUEST_4842 = 'Strange Sources',

    TANARIS_1 = 'Tanaris',
    TANARIS_2 = 'Tanaris',
    QUEST_2662 = 'Noggenfogger Elixir',
    QUEST_2874 = 'Deliver to MacKinley',
    QUEST_1691 = 'More Wastewander Justice',
    QUEST_113 = 'Inspect Part Analysis',

    STONETALON_1 = 'Stonetalon mountains',
    STONETALON_2 = 'Stonetalon mountains',
    QUEST_1096 = 'Gerenzo Wrenchwhistle',

    UNGORO_1 = 'Un\'goro Crater',
    UNGORO_2 = 'Un\'goro Crater',
    QUEST_3962 = 'It\'s Dangerous to Go Alone',
    QUEST_4245 = 'Chasing A-Me 01',
    QUEST_4292 = 'The Bait for Lar\'korwi',

    THOUSAND_NEEDLES_1 = 'Thousand Needles',
    THOUSAND_NEEDLES_2 = 'Thousand Needles',
    QUEST_1189 = 'Safety First',

    ARATHI_1 = 'Arathi highland',
    ARATHI_2 = 'Arathi highland',
    QUEST_652 = 'Breaking the Keystone',

    BADLANDS_1 = 'Badlands',
    BADLANDS_2 = 'Badlands',
    QUEST_737 = 'Forbidden Knowledge',
    QUEST_778 = 'This Is Going to Be Hard',
    QUEST_656 = 'Summoning the Princess',
    
    EASTERN_PLAGUELANDS_1 = 'Eastern Plaguelands',
    EASTERN_PLAGUELANDS_2 = 'Eastern Plaguelands',
    QUEST_5942 = 'Hidden Treasures',
    QUEST_6041 = 'When Smokey Sings, I Get Violent',
    QUEST_5265 = 'The Argent Hold',

    BLASTED_LANDS_1 = 'Blasted lands',
    BLASTED_LANDS_2 = 'Blasted lands',
    QUEST_3628 = 'You Are Rakh\'likh, Demon',

    STRANGLETHORN_VALLEY_1 = 'Stranglethorn valley',
    STRANGLETHORN_VALLEY_2 = 'Stranglethorn valley',
    QUEST_208 = 'Big Game Hunter',
    QUEST_600 = 'Venture Company Mining',
    QUEST_613 = 'Cracking Maury\'s Foot',
    QUEST_628 = 'Excelsior',
    QUEST_338 = 'The Green Hills of Stranglethorn',

    WESTERN_PLAGUELANDS_1 = 'Western Plaguelands',
    WESTERN_PLAGUELANDS_2 = 'Western Plaguelands',
    QUEST_5944 = 'In Dreams',
    QUEST_5051 = 'Two Halves Become One',
    QUEST_4985 = 'The Wildlife Suffers Too',

    SEARING_GORGE_1 = 'Searing gorge',
    SEARING_GORGE_2 = 'Searing gorge',
    QUEST_3481 = 'Trinkets...',

    BLACK_ROCK_1 = 'Black Rock',
    BLACK_ROCK_2 = 'Black Rock',
    QUEST_8996 = 'Return to Bodley',

    AN_WISDOM_KEEPER = 'The Loremaster',
    AD_WISDOM_KEEPER = 'Complete the quest achievements listed below.',
    AN_WISDOM_KEEPER_AZEROTH = 'Loremaster of Azeroth',
    AD_WISDOM_KEEPER_AZEROTH = 'Earn Azeroth\'s quests related achievements listed below.',
    AN_WISDOM_KEEPER_KALIMDOR = 'Loremaster of the Kalimdor',
    AD_WISDOM_KEEPER_KALIMDOR = 'Earn Kalimdor\'s quests related achievements listed below.',
    AN_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Loremaster of the Eastern Kingdoms',
    AD_WISDOM_KEEPER_EASTERN_KINGDOMS = 'Earn Eastern Kingdoms\' quests related achievements listed below.',
    AN_WISDOM_KEEPER_OUTLAND = 'Loremaster of Outland',
    AD_WISDOM_KEEPER_OUTLAND = 'Complete the Outland quest achievements listed below.',
    AR_WISDOM_KEEPER = 'The unspoken title of The Loremaster.',

    AN_RAGEFIRE_CHASM = 'Ragefire chasm',
    AD_RAGEFIRE_CHASM = 'Defeat Jergosh the Invoker.',
    AN_WAILING_CAVERNS = 'Wailing caverns',
    AD_WAILING_CAVERNS = 'Defeat Mutanus the Devourer.',
    AN_DEAD_MINES = 'Dead mines',
    AD_DEAD_MINES = 'Defeat Edwin VanCleef.',
    AN_SHADOWFANG_KEEP = 'Shadowfang keep',
    AD_SHADOWFANG_KEEP = 'Defeat Archmage Arugal.',
    AN_BLACKFATHOM_DEEPS = 'Blackfathom deeps',
    AD_BLACKFATHOM_DEEPS = 'Defeat Aku\'mai.',
    AN_JAIL = 'The Jail',
    AD_JAIL = 'Defeat Kam Deepfury.',
    AN_GNOMREGAN = 'Gnomregan',
    AD_GNOMREGAN = 'Defeat Mekgineer Thermaplugg.',
    AN_RAZORFEN_KRAUL = 'Razorfen kraul',
    AD_RAZORFEN_KRAUL = 'Defeat Charlga Razorflank.',
    AN_SCARLET_MONASTERY = 'Scarlet monastery',
    AD_SCARLET_MONASTERY = 'Defeat the commanders at the Scarlet Monastery.',
    AC_SCARLET_MONASTERY1 = 'Bloodmage Thalnos defeated',
    AC_SCARLET_MONASTERY2 = 'Arcanist Doan defeated',
    AC_SCARLET_MONASTERY3 = 'Herod defeated',
    AC_SCARLET_MONASTERY4 = 'High Inquisitor Whitemane defeated',
    AN_RAZORFEN_DOWNS = 'Razorfen downs',
    AD_RAZORFEN_DOWNS = 'Defeat Amnennar the Coldbringer and Plaguemaw the Rotting.',
    AC_RAZORFEN_DOWNS1 = 'Amnennar the Coldbringer defeated',
    AC_RAZORFEN_DOWNS2 = 'Plaguemaw the Rotting defeated',
    AN_ULDAMAN = 'Uldaman',
    AD_ULDAMAN = 'Defeat Archaedas.',
    AN_ZULFARRAK = 'Zul\'Farrak',
    AD_ZULFARRAK = 'Defeat Chief Ukorz Sandscalp.',
    AN_MARAUDON = 'Maraudon',
    AD_MARAUDON = 'Defeat Princess Theradras.',
    AN_SUNKEN_TEMPLE = 'Sunken temple',
    AD_SUNKEN_TEMPLE = 'Defeat Shade of Eranikus.',
    AN_NEW_EMPEROR = 'New emperor',
    AD_NEW_EMPEROR = 'Kill Emperor Dagran Thaurissan.',
    AN_BLACKROCK_DEPTHS = 'Clearing the depths',
    AD_BLACKROCK_DEPTHS = 'Kill following bosses in Black Rock Depths.',
    AC_BLACKROCK_DEPTHS1 = 'High Interrogator Gerstahn killed',
    AC_BLACKROCK_DEPTHS2 = 'Houndmaster Grebmar killed',
    AC_BLACKROCK_DEPTHS3 = 'General Angerforge killed',
    AC_BLACKROCK_DEPTHS4 = 'Golem Lord Argelmach killed',
    AC_BLACKROCK_DEPTHS5 = 'Lord Incendius killed',
    AC_BLACKROCK_DEPTHS6 = 'Water Stilgiss killed',
    AC_BLACKROCK_DEPTHS7 = 'Bael\'Gar killed',
    AN_BLACKROCK_PARTY = 'Party at the deep',
    AD_BLACKROCK_PARTY = 'Defeat all listed opponents in the Grumpy Glutton Inn',
    AC_BLACKROCK_PARTY1 = 'Ribbly Screwspigot defeated',
    AC_BLACKROCK_PARTY2 = 'Plugger Spazzring defeated',
    AC_BLACKROCK_PARTY3 = 'Hurley Blackbreath defeated',
    AC_BLACKROCK_PARTY4 = 'Phalanx defeated',
    AN_BLACKROCK_DEPTHS_FULL = 'Black Rock Depths',
    AD_BLACKROCK_DEPTHS_FULL = 'Earn following achievements related to Black Rock Depths.',
    AN_ARMOR_SWORD = 'Best defense is an attack',
    AD_ARMOR_SWORD = 'Loot Stone of the Earth from the body of defeated Panzor the Invincible in Black Rock Depths.',
    AN_BLACKROCK_SPIRE_BOTTOM = 'Lower Black Rock Spire',
    AD_BLACKROCK_SPIRE_BOTTOM = 'Kill Overlord Whyrmthalak.',
    AN_BLACKROCK_SPIRE_UPPER = 'Upper Black Rock Spire',
    AD_BLACKROCK_SPIRE_UPPER = 'Kill General Drakkisath.',
    AN_BLACKROCK_SPIRE = 'Invader of the Black Rock Spire',
    AD_BLACKROCK_SPIRE = 'Earn following achievements related to Black Rock Spire.',
    AN_DIRE_MAUL = 'Ruler of the Forgotten City',
    AD_DIRE_MAUL = 'Clear all Dire Maul parts of enemies.',
    AC_DIRE_MAUL1 = 'Alzzin the Wildshaper killed',
    AC_DIRE_MAUL2 = 'Prince Tortheldrin killed',
    AC_DIRE_MAUL3 = 'King Gordok defeated',
    AN_STRATHOLME_LIVE = 'Live quarter of the Stratholme',
    AD_STRATHOLME_LIVE = 'Defeat Balnazzar.',
    AN_STRATHOLME_DEAD = 'Dead quarter of the Stratholme',
    AD_STRATHOLME_DEAD = 'Kill Baron Rivendare.',
    AN_STRATHOLME = '"Savior" of the Stratholme',
    AD_STRATHOLME = 'Earn following achievements related to Stratholme.',
    AN_SCHOLOMANCE = 'Scholomance',
    AD_SCHOLOMANCE = 'Defeat Darkmaster Gandling.',
    AN_YOUNG_DEFENDER = 'Young defender of the Azeroth',
    AD_YOUNG_DEFENDER = 'Earn low-level dungeon achievements listed below.',
    AN_DEFENDER = 'Defender of the Azeroth',
    AD_DEFENDER = 'Earn dungeon achievements listed below.',
    AR_DEFENDER = 'The unspoken title of Defender of Azeroth.',

    AN_ONYXIA = 'Onyxia\'s Lair',
    AD_ONYXIA = 'Kill Onyxia.',
    AN_AQ20 = 'Ruins of Ahn\'Qiraj',
    AD_AQ20 = 'Kill Ossirian the Unscarred.',
    AN_ZULGURUB = 'Zul\'Gurub',
    AD_ZULGURUB = 'Drive Hakkar out of this world.',
    AN_RAGNAROS = 'Molten Core',
    AD_RAGNAROS = 'Defeat Ragnaros.',
    AN_BLACK_WING_LAIR = 'Black Wing Lair',
    AD_BLACK_WING_LAIR = 'Kill Nefarian.',
    AN_AQ40 = 'Temple of Ahn\'Qiraj',
    AD_AQ40 = 'Defeat C\'thun.',
    AN_NAXXRAMAS_SPIDERS = 'Spider quarter of Naxxramas',
    AD_NAXXRAMAS_SPIDERS = 'Kill Maexxna.',
    AN_NAXXRAMAS_PLAGUE = 'Plague quarter of Naxxramas',
    AD_NAXXRAMAS_PLAGUE = 'Kill Loatheb.',
    AN_NAXXRAMAS_MILITARY = 'Naxxramas military quarter',
    AD_NAXXRAMAS_MILITARY = 'Defeat four horsemen.',
    AN_NAXXRAMAS_CONSTRUCT = 'The abomination quarter of Naxxramas',
    AD_NAXXRAMAS_CONSTRUCT = 'Kill Thaddius.',
    AN_NAXXRAMAS_LAIR = 'Frost Wyrm\'s Lair',
    AD_NAXXRAMAS_LAIR = 'Defeat Kel\'Thuzad.',
    AN_NAXXRAMAS = 'Vanquisher of Naxxramas',
    AD_NAXXRAMAS = 'Earn following Naxxramas related achievements.',
    AN_YOUNG_HERO = 'Young hero of the Azeroth',
    AD_YOUNG_HERO = 'Earn simpliest raid achievements listed below.',
    AN_BLACKROCK_MASTER = 'Lord of the Black Rock',
    AD_BLACKROCK_MASTER = 'Earn following achievements related to the Black Rock dungeons and raids.',
    AN_HERO = 'Hero of the Azeroth',
    AD_HERO = 'Earn raid achievements listed below.',
    AR_HERO = 'The unspoken title of Hero of Azeroth.',
    AN_GREAT_HERO = 'Great Hero of the Azeroth',
    AD_GREAT_HERO = 'Earn raid and dungeon achievements listed below.',
    AR_GREAT_HERO = 'The unspoken title of Great Hero of Azeroth :)',

    AN_PVP_RANK_A1 = 'Private (Legacy)',
    AN_PVP_RANK_A2 = 'Corporal (Legacy)',
    AN_PVP_RANK_A3 = 'Sergeant (Legacy)',
    AN_PVP_RANK_A4 = 'Master Sergeant (Legacy)',
    AN_PVP_RANK_A5 = 'Sergeant Major (Legacy)',
    AN_PVP_RANK_A6 = 'Knight (Legacy)',
    AN_PVP_RANK_A7 = 'Knight-Lieutenant (Legacy)',
    AN_PVP_RANK_A8 = 'Knight-Captain (Legacy)',
    AN_PVP_RANK_A9 = 'Knight-Champion (Legacy)',
    AN_PVP_RANK_A10 = 'Lieutenant Commander (Legacy)',
    AN_PVP_RANK_A11 = 'Commander (Legacy)',
    AN_PVP_RANK_A12 = 'Marshal (Legacy)',
    AN_PVP_RANK_A13 = 'Field Marshal (Legacy)',
    AN_PVP_RANK_A14 = 'Grand Marshal (Legacy)',
    AN_PVP_RANK_H1 = 'Scout (Legacy)',
    AN_PVP_RANK_H2 = 'Grunt (Legacy)',
    AN_PVP_RANK_H3 = 'Sergeant (Legacy)',
    AN_PVP_RANK_H4 = 'Senior Sergeant (Legacy)',
    AN_PVP_RANK_H5 = 'First Sergeant (Legacy)',
    AN_PVP_RANK_H6 = 'Stone Guard (Legacy)',
    AN_PVP_RANK_H7 = 'Blood Guard (Legacy)',
    AN_PVP_RANK_H8 = 'Legionnaire (Legacy)',
    AN_PVP_RANK_H9 = 'Centurion (Legacy)',
    AN_PVP_RANK_H10 = 'Champion (Legacy)',
    AN_PVP_RANK_H11 = 'Lieutenant General (Legacy)',
    AN_PVP_RANK_H12 = 'General (Legacy)',
    AN_PVP_RANK_H13 = 'Warlord (Legacy)',
    AN_PVP_RANK_H14 = 'High Warlord (Legacy)',
    AD_PVP_RANK = 'Get the rank of the same name with this achievement.',
    AN_PVP_FIRST_KILL = 'PvP Victory',
    AD_PVP_FIRST_KILL = 'Claim your first honorable kill.',
    AC_PVP_FIRST_KILL = 'Claimed first honorable kill',
    AN_PVP_KILLS = '%d Honorable Kills',
    AD_PVP_KILLS = 'Get %d honorable kills.',
    AC_PVP_KILLS = 'Got %d honorable kills',

    AN_MOB_KILLS_1 = 'Killer',
    AN_MOB_KILLS_2 = 'Destroyer',
    AN_MOB_KILLS_3 = 'Crusher',
    AN_MOB_KILLS_4 = 'Head hunter',
    AN_MOB_KILLS_5 = 'Thunderstorm of the monsters',
    AN_MOB_KILLS_6 = 'Thunderstorm of all living things',
    AN_MOB_KILLS_7 = 'Omnipresent death',
    AD_MOB_KILLS = 'Kill %d monsters.',
    AC_MOB_KILLS = 'Killed %d monsters.',

    AN_REPS_1 = 'Someone likes me!',
    AD_REPS_1 = 'Raise any reputation to Exalted.',
    AC_REPS_1 = 'Raised any reputation to Exalted.',
    AN_REPS_2 = 'Two courtyards',
    AN_REPS_3 = 'Darling',
    AN_REPS_4 = 'Adored',
    AN_REPS_5 = 'Exalted',
    AN_REPS_6 = 'Venerable',
    AN_REPS_7 = 'Highly esteemed',
    AN_REPS_MORE = '%d Exalted Reputations',
    AD_REPS = 'Raise %d reputations to Exalted.',
    AC_REPS = 'Raised %d reputations to Exalted.',
    AR_REPS = 'The unspoken title is akin to the title of the achievement!',

    AN_HORDE_REPS = 'Voice of the Horde',
    AD_HORDE_REPS = 'Reach Exalted with the Horde factions listed below.',
    AC_HORDE_REPS_1 = 'Exalted with Orgrimmar.',
    AC_HORDE_REPS_2 = 'Exalted with the Darkspear Tribe.',
    AC_HORDE_REPS_3 = 'Exalted with Undercity.',
    AC_HORDE_REPS_4 = 'Exalted with Thunder Bluff.',
    AC_HORDE_REPS_5 = 'Exalted with Silvermoon.',

    AN_ALLIANCE_REPS = 'Alliance Herald',
    AD_ALLIANCE_REPS = 'Reach Exalted with the Alliance factions listed below.',
    AC_ALLIANCE_REPS_1 = 'Exalted with Stormwind.',
    AC_ALLIANCE_REPS_2 = 'Exalted with Darnassus.',
    AC_ALLIANCE_REPS_3 = 'Exalted with the Gnomeregan Exiles.',
    AC_ALLIANCE_REPS_4 = 'Exalted with Ironforge.',
    AC_ALLIANCE_REPS_5 = 'Exalted with Exodar.',

    AN_ARGENT_DAWN = 'Hand of Dawn',
    AD_ARGENT_DAWN = 'Reach Exalted with the Argent Dawn.',
    AN_BROOD_OF_NOZDORMU = 'Time Lord',
    AD_BROOD_OF_NOZDORMU = 'Reach Exalted with the Brood of Nozdormu.',
    AN_CENARION_CIRCLE = 'Defender of nature',
    AD_CENARION_CIRCLE = 'Reach Exalted with the Cenarion Circle.',
    AN_DARKMOON_FAIRE = 'Fulldarkmoon',
    AD_DARKMOON_FAIRE = 'Reach Exalted with the faction of Darkmoon Faire.',
    AN_ZANDALAR_TRIBE = 'Hakkar\'s horror',
    AD_ZANDALAR_TRIBE = 'Reach Exalted with the Zandalar Tribe.',
    AN_HYDRAXIANS = 'True Hydraxian',
    AD_HYDRAXIANS = 'Reach Exalted with the Hydraxian Waterlods.',
    AN_TIMBERMAW_HOLD = 'Not made of wood, but with a belly',
    AD_TIMBERMAW_HOLD = 'Reach Exalted with Timbermaw.',
    AN_PIRATES = 'Yar-r-r!',
    AD_PIRATES = 'Reach Honored with the Bloodsail Buccaneers.',
    AN_SHENDRALAR = 'Did I tell you what madness is?',
    AD_SHENDRALAR = 'Reach Exalted with Shen\'dralar.',

    AN_DEFILERS = 'For the Defilers!',
    AD_DEFILERS = 'Reach Exalted with Defilers.',
    AN_FROSTWOLF_CLAN = 'Frost wolf',
    AD_FROSTWOLF_CLAN = 'Reach Exalted with the Frostwolf Clan.',
    AN_WARSONG_OUTRIDERS = 'There is only one song',
    AD_WARSONG_OUTRIDERS = 'Reach Exalted with Warsong Outriders.',
    AN_HORDE_PVP_FRACTIONS = 'Honorary Warrior of the Horde',
    AD_HORDE_PVP_FRACTIONS = 'Reach Exalted with the following Horde Forces factions.',

    AN_LEAGUE_OF_ARATHOR = 'For Arathor!',
    AD_LEAGUE_OF_ARATHOR = 'Reach Exalted with the League of Arathor.',
    AN_STORMSPIKE_GUARD = 'Stormguard',
    AD_STORMSPIKE_GUARD = 'Reach Exalted with Stormspike Guards.',
    AN_SILVERWING_SENTINELS = 'Silver wings',
    AD_SILVERWING_SENTINELS = 'Reach Exalted with Silverwing Sentinels.',
    AN_ALLIANCE_PVP_FRACTIONS = 'Honorary Soldier of the Alliance',
    AD_ALLIANCE_PVP_FRACTIONS = 'Reach Exalted with the following Alliance Forces factions.',

    AN_BOLVAR_SLAYER = 'Coup in Stormwind',
    AD_BOLVAR_SLAYER = 'Defeat Highlord Bolvar Fordragon in Stormwind.',
    AN_MAGNI_SLAYER = 'New king',
    AD_MAGNI_SLAYER = 'Defeat King Magni Bronzebeard in Ironforge.',
    AN_MEKKATORQUE_SLAYER = 'Goblins > Gnomes',
    AD_MEKKATORQUE_SLAYER = 'Defeat High Tinker Mekkatorque in Ironforge.',
    AN_TYRANDE_SLAYER = 'Death to the priestess',
    AD_TYRANDE_SLAYER = 'Defeat Tyrande Whisperwind in Darnassus.',
    AN_VELEN_SLAYER = 'Putting Out the Light',
    AD_VELEN_SLAYER = 'Kill Prophet Velen.',

    AN_ALLIANCE_KINGS_SLAYER = 'Alliance Leaders',
    AD_ALLIANCE_KINGS_SLAYER = 'Defeat the leaders of the Alliance listed below.',

    AN_THRALL_SLAYER = 'New Warchief',
    AD_THRALL_SLAYER = 'Defeat Thrall in Orgrimmar.',
    AN_VOLJIN_SLAYER = 'Death to the messenger of spirits',
    AD_VOLJIN_SLAYER = 'Defeat Vol\'jin in Orgrimmar.',
    AN_SYLVANAS_SLAYER = 'Coup in Undercity',
    AD_SYLVANAS_SLAYER = 'Defeat Lady Sylvanas Windrunner in Undercity.',
    AN_CAIRNE_SLAYER = 'Head Cow',
    AD_CAIRNE_SLAYER = 'Defeat Cairne Bloodhoof in Thunder Bluff.',
    AN_LORTHEMAR_SLAYER = 'Killed in Quel\'Thalas',
    AD_LORTHERMAR_SLAYER = 'Kill Lor\'themar Theron.',

    AN_HORDE_KINGS_SLAYER = 'Horde Leaders',
    AD_HORDE_KINGS_SLAYER = 'Defeat the leaders of the Horde listed below.',

    AN_RACES_KILLER = 'Know Thy Enemy',
    AD_ALLIANCE_RACES_KILLER = 'Get a killing blow against all Alliance races.',
    AD_HORDE_RACES_KILLER = 'Get a killing blow against all Horde races.',
    AC_HUMAN_KILLED = 'Human killed',
    AC_NIGHTELF_KILLED = 'Night elf killed',
    AC_DWARF_KILLED = 'Dward killed',
    AC_GNOME_KILLED = 'Gnome killed',
    AC_ORC_KILLED = 'Orc killed',
    AC_TROLL_KILLED = 'Troll killed',
    AC_SCOURGE_KILLED = 'Undead killed',
    AC_TAUREN_KILLED = 'Tauren killed',
    AC_DRAENEI_KILLED = 'Draenei killed',
    AC_BLOODELF_KILLED = 'Blood elf killed',

    AN_CLASSES_KILLER = 'That Takes Class',
    AD_CLASSES_KILLER = 'Get a killing blow on one of each class.',
    AC_WARRIOR_KILLED = 'Warrior killed',
    AC_HUNTER_KILLED = 'Hunter killed',
    AC_ROGUE_KILLED = 'Rogue killed',
    AC_PRIEST_KILLED = 'Priest killed',
    AC_MAGE_KILLED = 'Mage killed',
    AC_WARLOCK_KILLED = 'Warlock killed',
    AC_DRUID_KILLED = 'Druid killed',
    AC_PALADIN_KILLED = 'Paladin killed',
    AC_SHAMAN_KILLED = 'Shaman killed',

    AN_ALTERAC_WIN = 'Victory in the Alterac Valley',
    AD_ALTERAC_WIN = 'Win the battle for Alterac Valley.',
    AN_ALTERAC_WINS = 'Alterac Valley Veteran',
    AD_ALTERAC_WINS = 'Win %d battles for Alterac Valley.',
    AN_WARSONG_WIN = 'Victory in the Gulch',
    AD_WARSONG_WIN = 'Win the battle for Warsong Gulch.',
    AN_WARSONG_WINS = 'Warsong Gulch Veteran',
    AD_WARSONG_WINS = 'Win %d battles for Warsong Gulch.',
    AN_ARATHI_WIN = 'Victory in the Basin',
    AD_ARATHI_WIN = 'Win the battle for Arathi Basin.',
    AN_ARATHI_WINS = 'Arathi Basin Veteran',
    AD_ARATHI_WINS = 'Win %d battles for Arathi Basin.',
    AN_EYE_WIN = 'Eye of the Storm Victory',
    AD_EYE_WIN = 'Win Eye of the Storm.',
    AN_EYE_WINS = 'Eye of the Storm Veteran',
    AD_EYE_WINS = 'Complete %d victories in Eye of the Storm.',

    AN_ALTERAC_KILLING_BLOWS = 'Valley Meat Grinder',
    AD_ALTERAC_KILLING_BLOWS = 'Make %d killing blows in a single battle for Alterac Valley and stay to the end of the battle.',
    AN_ALTERAC_GRAVEYARD_ASSAULT = 'Undertaker',
    AD_ALTERAC_GRAVEYARD_ASSAULT = 'Assault the graveyard while fighting for Alterac Valley and stay before the battle is over.',
    AN_ALTERAC_GRAVEYARD_ASSAULTS = 'There are never enough coffins',
    AD_ALTERAC_GRAVEYARD_ASSAULTS = 'Assault %d graveyards in a single battle for Alterac Valley and stay to the end of the battle.',
    AN_ALTERAC_GRAVEYARD_DEFEND = 'Guardian of the deceased',
    AD_ALTERAC_GRAVEYARD_DEFEND = 'Defend the graveyard while fighting for Alterac Valley and stay before the battle is over.',
    AN_ALTERAC_GRAVEYARD_DEFENDS = 'Guardian of all the dead',
    AD_ALTERAC_GRAVEYARD_DEFENDS = 'Defend %d graveyards in a single battle for Alterac Valley and stay to the end of the battle.',
    AN_ALTERAC_TOWER_ASSAULT = 'Now it\'s mine!',
    AD_ALTERAC_TOWER_ASSAULT = 'Assault the tower while fighting for Alterac Valley and stay before the battle is over.',
    AN_ALTERAC_TOWER_ASSAULTS = 'Now it\'s all mine!',
    AD_ALTERAC_TOWER_ASSAULTS = 'Assault %d towers in a single battle for Alterac Valley and stay to the end of the battle.',
    AN_ALTERAC_TOWER_DEFEND = 'Tower keeper',
    AD_ALTERAC_TOWER_DEFEND = 'Defend the tower while fighting for Alterac Valley and stay before the battle is over.',
    AN_ALTERAC_TOWER_DEFENDS = 'Towers keeper',
    AD_ALTERAC_TOWER_DEFENDS = 'Defend %d towers in a single battle for Alterac Valley and stay to the end of the battle.',
    AN_ALTERAC_MINE_CAPTURE = 'Frozen miner',
    AD_ALTERAC_MINE_CAPTURE = 'Assault the mine while fighting for Alterac Valley and stay before the battle is over.',
    AN_ALTERAC_MINE_CAPTURES = 'Frozen pikeman',
    AD_ALTERAC_MINE_CAPTURES = 'Assault %d mines in a single battle for Alterac Valley and stay to the end of the battle.',

    AN_WARSONG_KILLS = 'Military honor',
    AD_WARSONG_KILLS = 'Get %d honorable kills in a single battle for Warsong Gulch and stay to the end of the battle.',
    AN_WARSONG_FLAG_CAPTURE = 'Flag bearer',
    AD_WARSONG_FLAG_CAPTURE = 'Capture enemies flag while fighting for Warsong Gulch and stay before the battle is over.',
    AN_WARSONG_FLAG_CAPTURES = 'Great flag bearer',
    AD_WARSONG_FLAG_CAPTURES = 'Capture enemies flag %d times in a single battle for Warsong Gulch and stay to the end of the battle.',
    AN_WARSONG_FLAG_RETURN = 'Don\'t touch!',
    AD_WARSONG_FLAG_RETURN = 'Return your fraction flag to the base while fighting for Warsong Gulch and stay before the battle is over.',
    AN_WARSONG_FLAG_RETURNS = 'Don\'t touch anything!',
    AD_WARSONG_FLAG_RETURNS = 'Return %d your fraction flags to the base in a single battle for Warsong Gulch and stay to the end of the battle.',

    AN_ARATHI_BASE_ASSAULT = 'Conquistador',
    AD_ARATHI_BASE_ASSAULT = 'Assault a construction while fighting for Arathi Basin and stay before the battle is over.',
    AN_ARATHI_BASE_ASSAULTS = 'The famous conquistador',
    AD_ARATHI_BASE_ASSAULTS = 'Assault %d constructions in a single battle for Arathi Basin and stay to the end of the battle.',
    AN_ARATHI_BASE_DEFEND = 'Sentry',
    AD_ARATHI_BASE_DEFEND = 'Defend a construction while fighting for Arathi Basin and stay before the battle is over.',
    AN_ARATHI_BASE_DEFENDS = 'Honorary sentry',
    AD_ARATHI_BASE_DEFENDS = 'Defend %d constructions in a single battle for Arathi Basin and stay to the end of the battle.',

    AN_EYE_CAPTURE = 'Storm Capper',
    AD_EYE_CAPTURE = 'Personally capture the flag in Eye of the Storm and stay to the end of the battle.',
    AD_EYE_CAPTURES = 'Personally capture %d flags in a single battle of Eye of the Storm and stay to the end of the battle.',
    AN_EYE_GLORY = 'Bound for Glory',
    AD_EYE_GLORY = 'In a single Eye of the Storm match, capture the flag 3 times without dying.',
    AN_EYE_FAST_WIN = 'Flurry',
    AD_EYE_FAST_WIN = 'Win Eye of the Storm in under 6 minutes.',
    AN_EYE_BERSERK = 'Bloodthirsty Berserker',
    AD_EYE_BERSERK = 'Get a killing blow against another player while under the effects of the berserker buff in Eye of the Storm.',
    AN_EYE_IDEAL_VICTORY = 'The Perfect Storm',
    AD_EYE_IDEAL_VICTORY = 'Win Eye of the Storm with a score of 1500 to 0.',

    AN_BGS_KILLING_BLOWS = 'Deathbringer',
    AD_BGS_KILLING_BLOWS = 'Make %d killing blows on battlegrounds you did not leave.',
    AN_BGS_KILLS = 'Honor aggregator',
    AD_BGS_KILLS = 'Get %d honorable kills on battlegrounds you did not leave.',

    PROF_FIRST_AID = 'First Aid',
    PROF_FISHING = 'Fishing',
    PROF_COOKING = 'Cooking',
    PROF_ENCHANTING = 'Enchanting',
    PROF_TAILORING = 'Tailoring',
    PROF_ENGINEERING = 'Engineering',
    PROF_LEATHERWORKING = 'Leatherworking',
    PROF_ALCHEMY = 'Alchemy',
    PROF_BLACKSMITHING = 'Blacksmithing',
    PROF_HERBALISM = 'Herbalism',
    PROF_MINING = 'Mining',
    PROF_SKINNING = 'Skinning',
    PROF_JEWELCRAFTING = 'Jewelcrafting',
    SKILL_UNARMED = 'Unarmed',
    SKILL_RIDING = 'Riding',

    AN_PROFS_JOURNEYMAN = 'Journeyman',
    AD_PROFS_JOURNEYMAN = 'Raise the skill of any main profession to 75.',
    AN_PROFS_EXPERT = 'Expert',
    AD_PROFS_EXPERT = 'Raise the skill of any main profession to 150.',
    AN_PROFS_ARTISAN = 'Artisan',
    AD_PROFS_ARTISAN = 'Raise the skill of any main profession to 225.',
    AN_PROFS_ONE = 'Master',
    AD_PROFS_ONE = 'Raise the skill of any main profession to 300.',
    AN_PROFS_ONE_OUTLAND = 'Outlandish Master',
    AD_PROFS_ONE_OUTLAND = 'Raise the skill of any main profession to 375.',
    AN_PROFS_TWO = 'Handyman',
    AD_PROFS_TWO = 'Raise the skill of two main professions to 300 at the same time.',
    AC_PROFS_TWO = 'Raised the skill of two main professions to 300 at the same time.',
    AN_PROFS_TWO_OUTLAND = 'Outlandish Handyman',
    AD_PROFS_TWO_OUTLAND = 'Raise the skill of two main professions to 375 at the same time.',
    AC_PROFS_TWO_OUTLAND = 'Raised the skill of two main professions to 375 at the same time.',

    AN_FIRST_AID_JOURNEYMAN = 'Novice doctor',
    AD_FIRST_AID_JOURNEYMAN = 'Raise the skill of first aid to 75.',
    AN_FIRST_AID_EXPERT = 'Skillful doctor',
    AD_FIRST_AID_EXPERT = 'Raise the skill of first aid to 150.',
    AN_FIRST_AID_ARTISAN = 'Artisan doctor',
    AD_FIRST_AID_ARTISAN = 'Raise the skill of first aid to 225.',
    AN_FIRST_AID_MASTER = 'Field doctor',
    AD_FIRST_AID_MASTER = 'Raise the skill of first aid to 300.',
    AN_FIRST_AID_OUTLAND_MASTER = 'Outlandish doctor',
    AD_FIRST_AID_OUTLAND_MASTER = 'Raise the skill of first aid to 375.',
    AN_FISHING_JOURNEYMAN = 'Beginner angler',
    AD_FISHING_JOURNEYMAN = 'Raise the skill of fishing to 75.',
    AN_FISHING_EXPERT = 'Skillful angler',
    AD_FISHING_EXPERT = 'Raise the skill of fishing to 150.',
    AN_FISHING_ARTISAN = 'Artisan angler',
    AD_FISHING_ARTISAN = 'Raise the skill of fishing to 225.',
    AN_FISHING_MASTER = 'Famous angler',
    AD_FISHING_MASTER = 'Raise the skill of fishing to 300.',
    AN_FISHING_OUTLAND_MASTER = 'Outlandish angler',
    AD_FISHING_OUTLAND_MASTER = 'Raise the skill of fishing to 375.',
    AN_COOKING_JOURNEYMAN = 'Apprentice culinary',
    AD_COOKING_JOURNEYMAN = 'Raise the skill of cooking to 75.',
    AN_COOKING_EXPERT = 'Skillful cook',
    AD_COOKING_EXPERT = 'Raise the skill of cooking to 150.',
    AN_COOKING_ARTISAN = 'Smart cook',
    AD_COOKING_ARTISAN = 'Raise the skill of cooking to 225.',
    AN_COOKING_MASTER = 'Chef',
    AD_COOKING_MASTER = 'Raise the skill of cooking to 300.',
    AN_COOKING_OUTLAND_MASTER = 'Outlandish Chef',
    AD_COOKING_OUTLAND_MASTER = 'Raise the skill of cooking to 375.',
    AN_PROFS_SECONDARY = 'Both the priest and the reaper',
    AD_PROFS_SECONDARY = 'Raise the skill of all secondary professions to 300 at the same time.',
    AN_PROFS_SECONDARY_OUTLAND = 'Both the priest and the reaper, also in Outland',
    AD_PROFS_SECONDARY_OUTLAND = 'Raise the skill of all secondary professions to 375 at the same time.',
    AN_PROFS_FIVE = 'Genius is brilliant in everything',
    AN_PROFS_FIVE_OUTLAND = 'Outlandish Genius',
    AD_PROFS_FIVE = 'Earn profession achievements listed below.',
    AN_UNARMED_SKILL = 'Did Somebody Order a Knuckle Sandwich?',
    AD_UNARMED_SKILL = 'Raise the skill of unarmed combat to 350.',

    AN_EXPLORE_AZEROTH = 'Azeroth Explorer',
    AD_EXPLORE_AZEROTH = 'Explore the world of Azeroth!',
    AN_EXPLORE_KALIMDOR = 'Kalimdor Explorer',
    AD_EXPLORE_KALIMDOR = 'Explore locations of Kalimdor listed below.',
    AN_EXPLORE_EASTERN_KINGDOMS = 'Eastern Kingdoms Explorer',
    AD_EXPLORE_EASTERN_KINGDOMS = 'Explore locations of Eastern Kingdoms listed below.',
    AD_EXPLORE = 'Explore %s.',

    AN_SULFURAS = 'Sulfuras, Hand of Ragnaros',
    AD_SULFURAS = 'Wielder of Sulfuras, Hand of Ragnaros.',
    AN_THUNDER_FURY = 'Thunderfury, Blessed Blade of the Windseeker',
    AD_THUNDER_FURY = 'Wielder of Thunderfury, Blessed Blade of the Windseeker.',
    AN_ATIESH = 'Atiesh, Greatstaff of the Guardian',
    AD_ATIESH = 'Wielder of Atiesh, Greatstaff of the Guardian.',
    AN_BLACK_SCARAB = 'Scarab Lord',
    AD_BLACK_SCARAB = 'Wielder of Black Qiraji Resonating Crystal.',
    AN_RED_SCARAB = 'Why? Because It\'s Red!',
    AD_RED_SCARAB = 'Wielder of Red Qiraji Resonating Crystal.',
    
    AN_UNCOMMON_GEAR = 'Not so ordinary anymore',
    AD_UNCOMMON_GEAR = 'Equip yourself with items of uncommon or higher quality.',
    AN_RARE_GEAR = 'Superior',
    AD_RARE_GEAR = 'Equip yourself with items of rare (superior) or higher quality.',
    AN_EPIC_GEAR = 'Epic',
    AD_EPIC_GEAR = 'Equip yourself with items of epic or higher quality.',

    AN_STOCKING_UP = 'Stocking up',
    AD_STOCKING_UP = 'Craft 100 heavy runecloth bandages.',
    AC_STOCKING_UP = 'Crafted 100 heavy runecloth bandages',
    AN_STOCKING_UP_2 = 'Stocking up with usury',
    AD_STOCKING_UP_2 = 'Craft 500 heavy runecloth bandages.',
    AC_STOCKING_UP_2 = 'Crafted 500 heavy runecloth bandages',
    AN_STOCKING_UP_OUTLAND = 'Preparing for the Void',
    AD_STOCKING_UP_OUTLAND = 'Craft 100 heavy netherweave bandages.',
    AC_STOCKING_UP_OUTLAND = 'Crafted 100 heavy netherweave bandages',
    AN_STOCKING_UP_2_OUTLAND = 'Seriously Preparing for the Void',
    AD_STOCKING_UP_2_OUTLAND = 'Craft 500 heavy netherweave bandages.',
    AC_STOCKING_UP_2_OUTLAND = 'Crafted 500 heavy netherweave bandages',

    AN_FISHING_ROD = 'I choose the best for fishing',
    AD_FISHING_ROD = 'Take a win in a Stranglethorn Fishing Extravaganza and choose Arcanite Fishing Pole as your reward.',
    AN_FISHING_TRINKET = 'Real fish lover',
    AD_FISHING_TRINKET = 'Take a win in a Stranglethorn Fishing Extravaganza and choose Hook of the Master Angler as your reward.',

    AN_FISHING_COLLECTION = 'Fish Collection',
    AD_FISHING_COLLECTION = 'Fish out the following fishes in Azeroth.',
    AN_FISHING_OUTLAND_COLLECTION = 'Outlandish Collection',
    AD_FISHING_OUTLAND_COLLECTION = 'Fish out the following species in Outland.',
    AN_FISHING_WATER = 'Water from water',
    AD_FISHING_WATER = 'Fish out the substance of water.',
    AN_FISHING_RUM = 'I do not put down',
    AD_FISHING_RUM = 'Fish out the following types of rum.',
    AC_FISHING_RUM_BLACK = 'Rumsey Rum Black Label',
    AC_FISHING_RUM_WHITE = 'Rumsey Rum Light',
    AN_FISHING_RING = 'Gift out of Mordor',
    AD_FISHING_RING = 'Fish out The 1 Ring.',
    AN_FISHING_SKULL = 'Harbinger of a sad end',
    AD_FISHING_SKULL = 'Fish out Old Teamster\'s Skull.',
    AN_FISHING_SNAPPER = 'Great snapper catcher',
    AD_FISHING_SNAPPER = 'Fish snappers of the following sizes.',
    AC_FISHING_SNAPPER = '%d Pound Mud Snapper',
    AN_FISHING_SEA_BASS = 'Thunderstorm of perches',
    AD_FISHING_SEA_BASS = 'Fish redgills and groupers of the following sizes.',
    AC_FISHING_SEA_BASS = '%d Pound',
    AN_FISHING_SALMON = 'Salmon lover',
    AD_FISHING_SALMON = 'Fish salmons of the following sizes.',
    AC_FISHING_SALMON = '%d Pound Salmon',
    AN_FISHING_LOBSTER = 'Omar hunter',
    AD_FISHING_LOBSTER = 'Fish lobsters of the following sizes.',
    AC_FISHING_LOBSTER = '%d Pound Lobster',
    AN_FISHING_BIG_SIZE = 'Greatest Angler of Azeroth',
    AD_FISHING_BIG_SIZE = 'Complete the Large Fish achievements listed below.',
    AR_FISHING_BIG_SIZE = 'The unspoken title of Azeroth\'s Greatest Angler.',

    AN_COOKING_RECIPES_30 = 'Exploring goodies',
    AN_COOKING_RECIPES_50 = 'Nutritional life',
    AN_COOKING_RECIPES_60 = 'Food is my middle name',
    AN_COOKING_RECIPES_70 = 'Recipe master',
    AN_COOKING_RECIPES_80 = 'Adept of Azeroth dishes',
    AR_COOKING_RECIPES = 'The unspoken title of the Adept of Azeroth dishes.',
    AD_COOKING_RECIPES = 'Learn recipes for %d dishes.',
    AC_COOKING_RECIPES = 'Larned %d dishes recipes',

    AN_COOKING_SOUP = 'Soupbrewer',
    AN_COOKING_DESSERT = 'Pastry-cook',
    AN_COOKING_SQUID = 'Seafood on the table today',
    AN_COOKING_DUMPLINGS = 'Grandma\'s dumplings',
    AN_COOKING_CHOPS = 'Super nutritious chops',
    AD_COOKING_CREATE = 'Cook %s %d times.',
    AC_COOKING_CREATE = 'Cooked %d times',
    AN_COOKING_BIG_TABLE = 'Large festive table',
    AD_COOKING_BIG_TABLE = 'Complete the Cooking Large Amount achievements listed below.',

    AN_COOKING_FISHERMANS_FEAST = 'The Delight of My Lips',
    AN_COOKING_SPICY_HOT_TALBUK = 'A little of Talbuk for Me and You',
    AN_COOKING_SKULLFISH_SOUP = 'Penetrates to the Skull!',
    AN_COOKING_RAVAGER_DOG = 'Hot dog for Everyone!',

    AN_WB_AZUREGOS = 'The secret of the blue dragon',
    AD_WB_AZUREGOS = 'Defeat Azuregos.',
    AN_WB_KAZZAK = 'Demons will not pass (Legacy)',
    AD_WB_KAZZAK = 'Defeat Lord Kazzak.',
    AN_WB_KAZZAK_OUTLAND = 'I\'m the Master of My Fate',
    AD_WB_KAZZAK_OUTLAND = 'Defeat Doom Lord Kazzak in Hellfire Peninsula.',
    AN_WB_DOOMWALKER = 'Broken Doomwalker',
    AD_WB_DOOMWALKER = 'Defeat Doomwalker in Shadowmoon Valley.',
    AN_WB_YSONDRE = 'No room for girls in a nightmare',
    AD_WB_YSONDRE = 'Defeat Ysondre.',
    AN_WB_LETHON = 'Child of the emerald nightmare',
    AD_WB_LETHON = 'Defeat Lethon.',
    AN_WB_EMERISS = 'Emeriss, the traitor to life',
    AD_WB_EMERISS = 'Defeat Emeriss.',
    AN_WB_TAERAR = 'Nightmarish Taerar',
    AD_WB_TAERAR = 'Defeat Taerar.',
    AN_WB_EMERALD_DRAGONS = 'Emerald keeper',
    AD_WB_EMERALD_DRAGONS = 'Defeat all dragons of emerald nightmare.',
    AR_WB_EMERALD_DRAGONS = 'The unspoken title of Emerald keeper.',

    AN_DUEL = 'For the first time',
    AD_DUEL = 'Win in a duel.',
    AN_DUELS_10 = 'Duelist',
    AN_DUELS_25 = 'Skilled duelist',
    AN_DUELS_100 = 'Master duelist',
    AD_DUELS = 'Win in %d duels.',
    AC_DUELS = 'Won in %d duels',
    AN_GURUBASHI_1 = 'Gurubashi Arena Master',
    AD_GURUBASHI_1 = 'Loot the Arena Master trinket from the Gurubashi Arena.',
    AN_GURUBASHI_2 = 'Gurubashi Arena Grand Master',
    AD_GURUBASHI_2 = 'Complete Short John Mithril\'s quest to obtain the Arena Grand Master thinket.',
    AN_PARTICIPATE_IN_BGS = 'Call to Arms!',
    AD_PARTICIPATE_IN_BGS = 'Complete %d battlegrounds at max level.',
    AC_PARTICIPATE_IN_BGS = 'Completed %d battlegrounds at max level',

    EMOTE_LOVE1 = 'You love %s.',
    AN_LOVE = 'To All The Squirrels I\'ve Loved Before',
    AD_LOVE = 'Show the critters of Azeroth how much you /love them.',
    EMOTE_PAT1 = 'You gently pat %s.',
    AN_ARATHI_CATS = 'Cats first, then everything else',
    AD_ARATHI_CATS = '/pat the designated felines in Arathi Basin.',

    AN_ALTERAC_FAST_WIN = 'The Alterac Blitz',
    AD_ALTERAC_FAST_WIN = 'Win Alterac Valley in under 6 minutes.',
    AN_WARSONG_FAST_WIN = 'Warsong Expedience',
    AD_WARSONG_FAST_WIN = 'Win Warsong Gulch in under 7 minutes.',
    AN_ARATHI_FAST_WIN = 'Let\'s Get This Done',
    AD_ARATHI_FAST_WIN = 'Win Arathi Basin in under 6 minutes.',

    AN_ALTERAC_TOWER_DEFEND_TOTAL = 'Tower Defense',
    AD_ALTERAC_TOWER_DEFEND_TOTAL = 'Defend %d towers in Alterac Valley.',
    AN_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Alterac Grave Robber',
    AD_ALTERAC_GRAVEYARD_ASSAULT_TOTAL = 'Take %d graveyards in Alterac Valley.',
    AN_WARSONG_FLAG_CAPTURE_TOTAL = 'Flags Capturer',
    AD_WARSONG_FLAG_CAPTURE_TOTAL = 'Personally carry and capture %d flags in Warsong Gulch.',
    AN_WARSONG_FLAG_RETURN_TOTAL = 'Persistent Defender',
    AD_WARSONG_FLAG_RETURN_TOTAL = 'Return %d flags as a defender in Warsong Gulch.',
    AN_ARATHI_BASE_ASSAULT_TOTAL = 'Me and the Cappin\' Makin\' it Happen',
    AD_ARATHI_BASE_ASSAULT_TOTAL = 'Take %d flags in Arathi Basin.',
    AN_ARATHI_BASE_DEFEND_TOTAL = 'To The Rescue!',
    AD_ARATHI_BASE_DEFEND_TOTAL = 'Come the the defense of a base in Arathi Basin %d times by recapping the flag.',
    AN_ALTERAC_MOUNT_HORDE = 'Frostwolf Howler',
    AD_ALTERAC_MOUNT_HORDE = 'Obtain a Frostwolf Howler.',
    AN_ALTERAC_MOUNT_ALLIANCE = 'Stormpike Battle Charger',
    AD_ALTERAC_MOUNT_ALLIANCE = 'Obtain a Stormpike Battle Charger.',

    AN_ALTERAC_BOSS = 'Master of Alterac Valley',
    AD_ALTERAC_BOSS = 'Complete the Alterac Valley achievements listed below.',
    AN_WARSONG_BOSS = 'Master of Warsong Gulch',
    AD_WARSONG_BOSS = 'Complete the Warsong Gulch achievements listed below.',
    AN_ARATHI_BOSS = 'Master of Arathi Basin',
    AD_ARATHI_BOSS = 'Complete the Arathi Basin achievements listed below.',
    AN_EYE_BOSS = 'Master of Eye of the Storm',
    AD_EYE_BOSS = 'Complete the Eye of the Storm achievements listed below.',
    AN_BATTLEMASTER = 'Battlemaster',
    AD_BATTLEMASTER = 'Complete the battleground achievements listed below.',
    AR_BATTLEMASTER = 'The unspoken title of Battlemaster.',

    AN_LEEROY = 'Leeeeeeeeeeeeeroy!',
    AD_LEEROY = 'Kill 50 rookery whelps within 15 seconds.',
    AR_LEEROY = 'The unspoken title Jenkins.',
    AN_BWL_DUO = 'Double breathing',
    AD_BWL_DUO = 'Kill Ebonroc and Flamegor within 45 seconds.',
    AN_ANUBREKHAN_WITHOUT_MOBS = 'One bad spider',
    AD_ANUBREKHAN_WITHOUT_MOBS = 'Slay Anub\'Rekhan, leaving both crypt guards alive.',
    AN_FAERLINA_WITHOUT_MOBS = 'The non-lonely widow',
    AD_FAERLINA_WITHOUT_MOBS = 'Slay Grand Widow Faerlina, leaving all the worshipers and followers of Naxxramas alive.',
    AN_SAPPHIRONE_WITH_ALL_ALIVE = 'We won\'t submit to ice',
    AD_SAPPHIRONE_WITH_ALL_ALIVE = 'Defeat Sapphirone so that all 40 raid members remain alive.',
    AN_ARACHNOPHOBIA = 'Arachnophobia',
    AD_ARACHNOPHOBIA = 'Defeat Maexxna in Naxxramas within 20 minutes of Anub\'Rekhan\'s death.',
    AN_FOUR_TOGETHER = 'And they would all go down together',
    AD_FOUR_TOGETHER = 'Defeat the 4 Horsemen in Naxxramas, ensuring they all die within 15 seconds of each other.',

    AN_THANKS = 'I\'m myself, you know, a developer',
    AD_THANKS = 'Was especially helpful in developing, testing, translating or promoting Classic Achievements.',
    AR_THANKS = 'Infinite gratitude :)',

    AN_QUESTS_HELLFIRE_PENINSULA = 'To Hellfire and Back',
    AD_QUESTS_HELLFIRE_PENINSULA = 'Complete the Hellfire Peninsula storylines listed below.',
    TBC_QUEST_10388 = 'Disrupt the Burning Legion',
    TBC_QUEST_10389 = 'Cruel\'s Intentions',
    TBC_QUEST_10876 = 'The Hand of Kargath',
    TBC_QUEST_10258 = 'Spinebreaker Post',
    TBC_QUEST_9406 = 'The Mag\'har',
    TBC_QUEST_9370 = 'Falcon Watch',
    TBC_QUEST_10351 = 'Cenarion Post',

    TBC_QUEST_10397 = 'Disrupt the Burning Legion',
    TBC_QUEST_10400 = 'Overthrow the Overlord',
    TBC_QUEST_9545 = 'In Search of Sedai',
    TBC_QUEST_10935 = 'The Exorcism of Colonel Jules',
    TBC_QUEST_10937 = 'Drill the Drillmaster',
    TBC_QUEST_9383 = 'Temple of Telhamat',
    TBC_QUEST_10630 = 'Green, But Not Orcs',
    
    AN_QUESTS_ZANGARMASH = 'Mysteries of the Marsh',
    AD_QUESTS_ZANGARMASH = 'Complete the Zangarmarsh storylines listed below.',
    TBC_QUEST_9772 = 'Swamprat Post',
    TBC_QUEST_9904 = 'Zabra\'jin',
    TBC_QUEST_10118 = 'The Defense of Zabra\'jin',
    TBC_QUEST_9803 = 'Draenei Diplomacy',
    TBC_QUEST_9783 = 'Telredor',
    TBC_QUEST_9902 = 'Orebor Harborage',
    TBC_QUEST_9709 = 'Don\'t Eat THOSE Mushrooms!',
    TBC_QUEST_9732 = 'Draining the Marsh',
    TBC_QUEST_9788 = 'Saving the Sporeloks',
    TBC_QUEST_9726 = 'A Trip With the Sporelings',
    
    AN_QUESTS_TERROKAR = 'Terror of Terokkar',
    AD_QUESTS_TERROKAR = 'Complete the Terokkar Forest storylines listed below.',
    TBC_QUEST_10879 = 'The Skettis Offensive',
    TBC_QUEST_10881 = 'Refugee Caravan',
    TBC_QUEST_10915 = 'Sha\'tari Base Camp',
    TBC_QUEST_9951 = 'The Warden\'s Secret',
    TBC_QUEST_10042 = 'Allerian Stronghold',
    TBC_QUEST_10043 = 'Stonebreaker Hold',
    
    AN_QUESTS_NAGRAND = 'Nagrand Slam',
    AD_QUESTS_NAGRAND = 'Complete the Nagrand storylines listed below.',
    TBC_QUEST_10172 = 'Birth of a Warchief',
    TBC_QUEST_9977 = 'The Ring of Blood',
    TBC_QUEST_9853 = 'Throne of the Elements',
    TBC_QUEST_9934 = 'Lantresor of the Blade',
    TBC_QUEST_9868 = 'The Murkblood',
    TBC_QUEST_9937 = 'Threats to Nagrand',
    TBC_QUEST_9852 = 'The Ultimate Bloodsport',
    TBC_QUEST_9925 = 'Encountering the Ethereals',
    TBC_QUEST_9955 = 'The Adventures of Corki',
    TBC_QUEST_9933 = 'Lantresor of the Blade',
    TBC_QUEST_9873 = 'The Murkblood',
    TBC_QUEST_10011 = 'Threats to Nagrand',
    
    AN_QUESTS_BLADES_EDGE_MTNS = 'On the Blade\'s Edge',
    AD_QUESTS_BLADES_EDGE_MTNS = 'Complete the Blade\'s Edge Mountains storylines listed below..',
    TBC_QUEST_10504 = 'Sylvanaar',
    TBC_QUEST_10671 = 'Toshley\'s Station',
    TBC_QUEST_10806 = 'The Gronn Threat',
    TBC_QUEST_10505 = 'Thunderlord Stronghold',
    TBC_QUEST_10742 = 'Reunion',
    TBC_QUEST_10867 = 'The Mok\'Nathal',
    TBC_QUEST_10748 = 'Ruuan Weald',
    
    AN_QUESTS_NETHERSTORM = 'Into the Nether',
    AD_QUESTS_NETHERSTORM = 'Complete the Netherstorm storylines listed below.',
    TBC_QUEST_10409 = 'Socrethar',
    TBC_QUEST_10240 = 'The Violet Tower',
    TBC_QUEST_10249 = 'Protect Area 52!',
    TBC_QUEST_10439 = 'Destroying the All-Devouring',
    TBC_QUEST_10221 = 'Building the X-52 Nether-Rocket',
    TBC_QUEST_10276 = 'The Consortium',
    
    AN_QUESTS_SHADOWMOON = 'Shadow of the Betrayer',
    AD_QUESTS_SHADOWMOON = 'Complete the Shadowmoon Valley storylines listed below.',
    TBC_QUEST_10744 = 'News of Victory',
    TBC_QUEST_11041 = 'Netherwing Ledge',
    TBC_QUEST_10645 = 'The First Death Knight',
    TBC_QUEST_10651 = 'Borrowed Power',
    TBC_QUEST_11052 = 'Akama\'s Promise',
    TBC_QUEST_10588 = 'The Cipher of Damnation',
    TBC_QUEST_10679 = 'Anti-Demon Weapons',
    TBC_QUEST_10808 = 'The Dark Conclave',

    HEROIC_NAME_PATTERN = 'Heroic: %s',
    HEROIC_DESCRIPTION_PATTERN = '%s on Heroic Difficulty',

    AN_HELLFIRE_RAMPARTS = 'Hellfire Ramparts',
    AD_HELLFIRE_RAMPARTS = 'Defeat the leaders of Hellfire Ramparts',
    AC_BOSS_17308 = 'Omor the Unscarred',
    AC_BOSS_17537 = 'Vazruden the Herald',

    AN_BLOOD_FURNACE = 'The Blood Furnace',
    AD_BLOOD_FURNACE = 'Defeat Keli\'dan the Breaker',

    AN_SLAVE_PENS = 'The Slave Pens',
    AD_SLAVE_PENS = 'Defeat Quagmirran',

    AN_UNDERBOG = 'Underbog',
    AD_UNDERBOG = 'Defeat The Black Stalker',

    AN_MANA_TOMBS = 'Mana-Tombs',
    AD_MANA_TOMBS = 'Defeat Nexus-Prince Shaffar',

    AN_AUCHENAI_CRYPTS = 'Auchenai Crypts',
    AD_AUCHENAI_CRYPTS = 'Defeat Exarch Maladaar',

    AN_OLD_HILLSBRAD = 'The Escape From Durnholde',
    AD_OLD_HILLSBRAD = 'Defeat Epoch Hunter',

    AN_SETHEKK_HALLS = 'Sethekk Halls',
    AD_SETHEKK_HALLS = 'Defeat Talon King Ikiss',

    AN_STEAMVAULT = 'The Steamvault',
    AD_STEAMVAULT = 'Defeat Warlord Kalithresh',

    AN_SHADOW_LABYRINTH = 'Shadow Labyrinth',
    AD_SHADOW_LABYRINTH = 'Defear Murmur',

    AN_SHATTERED_HALLS = 'The Shattered Halls',
    AD_SHATTERED_HALLS = 'Defeat Warchief Kargath Bladefist',

    AN_BLACK_MORASS = 'Opening of the Dark Portal',
    AD_BLACK_MORASS = 'Defeat Aeonus',

    AN_BOTANICA = 'The Botanica',
    AD_BOTANICA = 'Defeat Warp Splinter',

    AN_MECHANAR = 'The Mechanar',
    AD_MECHANAR = 'Defeat Pathaleon the Calculator',

    AN_ARCATRAZ = 'The Arcatraz',
    AD_ARCATRAZ = 'Defeat Harbringer Skyriss',

    AN_TBC_DUNGEONS = 'Outland Dungeon Hero',
    AD_TBC_DUNGEONS = 'Complete the Burning Crusade Heroic dungeon achievements listed below.',

    AN_RAVEN_LORD = 'Raven Lord',
    AD_RAVEN_LORD = 'Obtain the very rare Reins of the Raven Lord.',

    AN_KARAZHAN = 'Karazhan',
    AD_KARAZHAN = 'Defeat Prince Malchezaar in Karazhan.',

    AN_GRUUL = 'Gruul\'s Lair',
    AD_GRUUL = 'Defeat Gruul the Dragonkiller in Gruul\'s Lair.',

    AN_MAGTHERIDON = 'Magtheridon\'s Lair',
    AD_MAGTHERIDON = 'Defeat Magtheridon in Magtheridon\'s Lair.',

    AN_TBC_PHASE_1 = 'Outland Phase One Raider',
    AD_TBC_PHASE_1 = 'Complete the Burning Crusade phase one raid achievements listed below.',
    AN_TBC_PHASE_2 = 'Outland Phase Two Raider',
    AD_TBC_PHASE_2 = 'Complete the Burning Crusade phase two raid achievements listed below.',

    FACTION_946 = 'Honor Hold',
    FACTION_947 = 'Thrallmar',
    FACTION_942 = 'Cenarion Expedition',
    FACTION_1011 = 'Lower City',
    FACTION_989 = 'Keepers of Time',
    FACTION_935 = 'The Sha\'tar',

    AN_TBC_DUNGEON_REPUTATIONS = 'The Burning Crusader',
    AD_TBC_DUNGEON_REPUTATIONS = 'Raise all of The Burning Crusade dungeon reputations to Exalted.',

    AN_SHATTRATH_REP = 'Shattrath Divided',
    AD_SHATTRATH_REP = 'Earn Exalted status with The Scryers or The Aldor.',

    AN_OGRILA = 'A Quest a Day Keeps the Ogres at Bay',
    AD_OGRILA = 'Earn Exalted status within Ogri\'la.',

    AN_SPOREGGAR = 'The Czar of Sporeggar',
    AD_SPOREGGAR = 'Earn Exalted status with Sporeggar.',

    AN_CONSORTIUM = 'Chief Exalted Officer',
    AD_CONSORTIUM = 'Earn Exalted status with The Consortium.',

    AN_MAGHAR = 'Mag\'har of Draenor',
    AD_MAGHAR = 'Earn Exalted status with The Mag\'har.',

    AN_KURENAI = 'Oh My, Kurenai',
    AD_KURENAI = 'Earn Exalted status with the Kurenai.',

    AN_NETHERWINGS = 'On Wings of Nether',
    AD_NETHERWINGS = 'Earn Exalted status with Netherwing.',

    AN_SKYSHATTERED = 'Skyshattered',
    AD_SKYSHATTERED = 'Defeat Captain Skyshatter in the Dragonmaw race on Netherwing Ledge.',

    AN_AMETHYST_EYE = 'The Violet Eye',
    AD_AMETHYST_EYE = 'Earn Exalted status with The Violet Eye.',

    AN_SCALE_OF_THE_SANDS = 'The Scale of the Sands',
    AD_SCALE_OF_THE_SANDS = 'Earn Exalted status with The Scale of the Sands.',

    AN_ASHTONGUE_DEATHSWORN = 'Sworn to the Deathsworn',
    AD_ASHTONGUE_DEATHSWORN = 'Earn Exalted status with the Ashtongue Deathsworn.',

    AN_SHATTERED_SUN = 'You\'re So Offensive',
    AD_SHATTERED_SUN = 'Earn Exalted status with the Shattered Sun Offensive.',

    AN_MR_PINCHY = 'Mr. Pinchy!',
    AD_MR_PINCHY = 'Fish out Mr. Pinchy in Outland.',

    EXPLORE_OUTLAND_NAME_PATTERN = 'Explore %s',
    AD_EXPLORE_HELLFIRE_PENINSULA = 'Explore Hellfire Peninsula, revealing the covered areas of the world map.',
    AD_EXPLORE_ZANGARMASH = 'Explore Zangarmarsh, revealing the covered areas of the world map.',
    AD_EXPLORE_NAGRAND = 'Explore Nagrand, revealing the covered areas of the world map.',
    AD_EXPLORE_TERROKAR = 'Explore Terokkar Forest, revealing the covered areas of the world map.',
    AD_EXPLORE_BLADES_EDGE_MTNS = 'Explore Blade\'s Edge Mountains, revealing the covered areas of the world map.',
    AD_EXPLORE_NETHERSTORM = 'Explore Netherstorm, revealing the covered areas of the world map.',
    AD_EXPLORE_SHADOWMOON = 'Explore Shadowmoon Valley, revealing the covered areas of the world map.',
    AN_EXPLORE_OUTLAND = 'Outland Explorer',
    AD_EXPLORE_OUTLAND = 'Explore the regions of Outland.',
    AN_EXPLORER = 'Universal Explorer',
    AD_EXPLORER = 'Explore all the lands of Azeroth and Outland.',
    AR_EXPLORER = 'The unspoken title of The Explorer.',

    AD_EXPLORE_EVERSONG_WOODS = 'Explore Eversong Woods, revealing the covered areas of the world map.',
    AD_EXPLORE_GHOSTLANDS = 'Explore Ghostlands, revealing the covered areas of the world map.',
    AD_EXPLORE_AZUREMYST_ISLE = 'Explore Azuremyst Isle, revealing the covered areas of the world map.',
    AD_EXPLORE_BLOODMYST_ISLE = 'Explore Bloodmyst Isle, revealing the covered areas of the world map.',

    AN_MIDDLE_RARE = 'Medium Rare',
    AD_MIDDLE_RARE = 'Kill one of the extremely rare and hard to find Outland creatures listed below.',
    AN_BLOODY_RARE = 'Bloody Rare',
    AD_BLOODY_RARE = 'Kill all of the extremely rare and hard to find Outland creatures listed below.',
    TBC_NPC_18695 = 'Ambassador Jerrikar',
    TBC_NPC_18682 = 'Bog Lurker',
    TBC_NPC_18697 = 'Chief Engineer Lorthander',
    TBC_NPC_18681 = 'Coilfang Emissary',
    TBC_NPC_18694 = 'Collidus the Warp-Watcher',
    TBC_NPC_18689 = 'Crippler',
    TBC_NPC_18686 = 'Doomsayer Jurim',
    TBC_NPC_18698 = 'Ever-Core the Punisher',
    TBC_NPC_18678 = 'Fulgorge',
    TBC_NPC_17144 = 'Goretooth',
    TBC_NPC_18692 = 'Hemathion',
    TBC_NPC_18696 = 'Kraator',
    TBC_NPC_18680 = 'Marticar',
    TBC_NPC_18677 = 'Mekthorg the Wild',
    TBC_NPC_18690 = 'Morcrush',
    TBC_NPC_20932 = 'Nuramoc',
    TBC_NPC_18685 = 'Okrek',
    TBC_NPC_18693 = 'Speaker Mar\'grom',
    TBC_NPC_18683 = 'Voidhunter Yar',
    TBC_NPC_18679 = 'Vorakem Doomspeaker',

    AN_PREPATCH_QUEST = 'Battle for the Dark Portal',
    AD_PREPATCH_QUEST = 'Participant in the Battle for the Dark Portal. Wielder of the Tabard of the Protector.',

    AN_RIDING_75 = 'Giddy Up!',
    AD_RIDING_75 = 'Learn the Apprentice Riding skill.',
    AN_RIDING_150 = 'Fast and Furious',
    AD_RIDING_150 = 'Learn the Journeyman Riding skill.',
    AN_RIDING_225 = 'Into the Wild Blue Yonder',
    AD_RIDING_225 = 'Learn the Expert Riding skill.',
    AN_RIDING_300 = 'Breaking the Sound Barrier',
    AD_RIDING_300 = 'Learn the Master Riding skill.',

    AN_ATTUNE_SHATTERED_HALLS = 'Hotter than Hell',
    AD_ATTUNE_SHATTERED_HALLS = 'Obtain the Shattered Halls Key.',
    AN_ATTUNE_ARCATRAZ = 'Infiltrating the Arcatraz',
    AD_ATTUNE_ARCATRAZ = 'Obtain the Key to the Arcatraz.',
    AN_ATTUNE_KARAZHAN = 'The Master\'s Touch',
    AD_ATTUNE_KARAZHAN = 'Obtain The Master\'s Key.',
    AN_ATTUNE_NIGHT_BANE = 'Digging Up the Past',
    AD_ATTUNE_NIGHT_BANE = 'Obtain the Blackened Urn.',
    AN_ATTUNE_SSC = 'Access to the Serpentshrine Cavern',
    AD_ATTUNE_SSC = 'Get access to the Serpentshrine Cavern.',
    AN_ATTUNE_EYE = 'The Eye',
    AD_ATTUNE_EYE = 'Obtain The Tempest Key.',
    AN_ATTUNE_HYJAL = 'The Vials of Eternity',
    AD_ATTUNE_HYJAL = 'Feed Soridormi from the Vials of Eternity and gain access to the Hujal Summit.',
    AN_ATTUNE_BLACK_TEMPLE = 'Entry Into the Black Temple',
    AD_ATTUNE_BLACK_TEMPLE = 'Obtain the Medallion of Karabor.',

    AN_SSC = 'Serpentshrine Cavern',
    AD_SSC = 'Defeat bosses listed below inside Serpentshrine Cavern.',
    AC_KILL_HYDROS = 'Hydross the Unstable',
    AC_KILL_LURKER = 'The Lurker Below',
    AC_KILL_LEOTHERAS = 'Leotheras the Blind',
    AC_KILL_KARATHRESS = 'Fathom-Lord Karathress',
    AC_KILL_MOROGRIM = 'Morogrim Tidewalker',
    AC_KILL_VASHJ = 'Lady Vashj',
    AN_TK = 'Tempest Keep',
    AD_TK = 'Defeat bosses listed below inside The Eye raid instance.',
    AC_KILL_ALAR = 'Al\'ar',
    AC_KILL_VOID_REAVER = 'Void Reader',
    AC_KILL_SOLARIAN = 'High Astromancer Solarian',
    AC_KILL_KAELTHAS = 'Kael\'thas Sunstrider'

})